### PR TITLE
Increase code maintainability（增加代码可维护性）

### PR DESCRIPTION
**Pull request by xAnYan**
Only the readable part was modified. I want to know what is zszjj/zspjj/ztdx/szbhwy/spbhwy/bhxz...
（仅修改了可读部分，请问zszjj/zspjj/ztdx/szbhwy/spbhwy/bhxz是什么……）

### CODE REVIEW

**Comment by xAnYan** [comment]
ps. python allows variable names named directly in Chinese. So you can write codes like `北京 = self.lineEdit_2.text()` and it will run properly.

**Comment by xAnYan** [comment]
but why there's even a `beijing` there??

**Comment by MrXiaoM** [comment]
> but why there's even a `beijing` there??

`beijing` may means `背景` (`background`)

**Comment by MrXiaoM** [comment]
By checking `/ui/night.png`, That's what I can help you.
| Shorten Pinyin | Chinese | English |
| ---- | ---- | ---- |
| zspjj | 字水平间距 | Word horizontal spacing |
| zszjj | 字竖直间距 | Word vertical spacing |
| ztdx | 字体大小 | Font size |
| spbhwy | 水平笔画位移 | Stroke horizontal shifting |
| szbhwy | 水平笔画位移 | Stroke vertical shifting |
| bhxz | 笔画旋转 | Stroke rotating |

**Comment by mind-dance** [comment]
感谢PR，代码已重构

**Pull request closed without merging**
